customer: ""

aml_experiment_details:
  compute_name: oor-testing
  env_name: oor-environment
  env_version: 57
  src_dir: "."

performance_evaluation:
  inputs:
    datastore: "dataset_oor_v2_2"
    ground_truth_rel_path: "processed-dataset-oor-v2-2"
    predictions_rel_path: "inference/v2-2/v2.2"
  outputs:
    datastore: "dataset_oor_v2_2"
    output_rel_path: "evaluation/v2-2/v2.2_test"
  dataset_name: "v2-2"
  model_name: "yolov8m_1280_v2.2"
  ground_truth_image_shape: [3840, 2160]
  predictions_image_shape: [1280, 720]
  prediction_labels_rel_path: "detected_labels"
  splits: ["train", "val", "test"]
  target_classes: [2, 3, 4]
  sensitive_classes: [0, 1]
  target_classes_conf: 0.7  # null means all predictions are used, custom COCO considers this threshold also for sensitive classes
  sensitive_classes_conf: null  # null means all predictions are used, only for TBA evaluation
  plot_pr_curves: True

training_pipeline:
  model_parameters:
    img_size: 1280
    batch: 0.85
    epochs: 500
    n_classes: 5
    name_classes: ["person", "license plate", "container", "mobile toilet", "scaffolding"]
    # The following settings are ignored in sweep mode and will instead be taken from the sweep_config file.
    patience: 100
    cos_lr: True
    dropout: 0.0
    seed: 0
    box: 7.5
    cls: 0.5
    dfl: 1.5
  inputs:
    datastore_path: "dataset_oor_v2_2"
    training_data_rel_path: "processed-dataset-oor-v2-2"
    model_weights_rel_path: "model"
    model_name: "best_yolo11m_coco_161024.pt"
    config_file: "train_data_augment_config.json" # can be an empty string or omitted entirely
    sweep_config: "sweep_config.json"
  outputs:
    project_datastore_path: "dataset_oor_v2_2"
    project_rel_path: "model"
  sweep_mode: False  # Set to true to run a hyperparameter sweep based on inputs/sweep_config

wandb:
  api_key: ""
  mode: "offline"

logging:
  loglevel_own: DEBUG  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "yolo_model_development_kit", "performance_evaluation", "training_pipeline"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: WARNING
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  ai_instrumentation_key: "AI_INSTRUMENTATION_KEY"
