customer: ""

aml_experiment_details:
  compute_name: oor-testing
  env_name: yolo-environment
  env_version: 18
  src_dir: "."

inference_pipeline:
  model_params:
    batch_size: 1  # batch size does not have an effect for SAHI
    img_size: [1024, 2048]  # [height, width]
    conf: 0.0001
  inputs:
    datastore_path: "annotations_datastore"
    inference_data_rel_path: "annotations-projects/07-25-2022_120550_UTC/ORBS-base/first-split/images/test/"
    model_weights_rel_path: "yolo11/trained_models"
    model_name: "yolo11m_orbs_lilac_spaceship-2.engine"
  outputs:
    datastore_path: "annotations_datastore"  # empty string "" means same as input datastore
    output_rel_path: "yolo11/inference/tensorrt_test/yolo11m_engine"
    detections_subfolder: ""
    labels_subfolder: "test"
  sahi_params:
    model_type: "ultralytics"
    slice_height: 2048
    slice_width: 2048
    overlap_height_ratio: 0.2
    overlap_width_ratio: 0.2
  target_classes: []
  sensitive_classes: [0, 1]
  target_classes_conf: null  # null means conf is taken from model_params
  sensitive_classes_conf: null  # null means conf is taken from model_params
  output_image_size: [8000, 4000]  # [width, height] - null means keep original size
  save_detection_images: False
  save_detection_labels: True
  save_all_images: False  # If True, all images will be saved regardless of whether they contain target class objects
  use_sahi: False

model_conversion:
  datastore_path: "annotations_datastore"
  model_weights_rel_path: "yolo11/trained_models/"
  input_model_name: "yolo11m_orbs_lilac_spaceship-2.pt"
  output_model_name: "yolo11m_orbs_lilac_spaceship-2.engine"
  overwrite_if_exists: True
  image_size: [1024, 2048]  # [height, width]
  batch_size: 1

performance_evaluation:
  inputs:
    datastore: "annotations_datastore"
    ground_truth_rel_path: "annotations-projects/07-25-2022_120550_UTC/ORBS-base/first-split"
    predictions_rel_path: "yolo11/inference/ORBS-base-test/yolo11s_base"
  outputs:
    datastore: "annotations_datastore"
    output_rel_path: "yolo11/evaluation/ORBS-base-test/yolo11s_base"
  categories_json_path: "categories_eval_baas_v5.json"
  mapping_json_path: "groupings_wheelchairs_bias_analysis.json"
  dataset_name: "ORBS-base"
  model_name: "yolo11s"
  predictions_image_shape: [8000, 4000]
  prediction_labels_rel_path: "labels"
  splits: ["test"]
  target_classes: []
  sensitive_classes: [0, 1]
  target_classes_conf: 0.7  # null means all predictions are used, custom COCO considers this threshold also for sensitive classes
  sensitive_classes_conf: null  # null means all predictions are used, only for TBA evaluation
  plot_curves: True
  plot_sml: True  # Whether to differentiate between S, M, and L (slower)
  plot_conf_range: [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1]  # Confidence values for PR curves
  plot_logx: True  # Use log scale for x-axis
  is_bias_analysis: False

training_pipeline:
  model_parameters:
    img_size: 1280
    batch: 0.85
    epochs: 500
    n_classes: 5
    name_classes: ["person", "license plate", "container", "mobile toilet", "scaffolding"]
    cache: True  # cache dataset in RAM
    # The following settings are ignored in sweep mode and will instead be taken from the sweep_config_file.
    patience: 100
    cos_lr: True
    dropout: 0.0
    seed: 0
    box: 7.5
    cls: 0.5
    dfl: 1.5
  inputs:
    datastore_path: "dataset_oor_v2_2"
    training_data_rel_path: "processed-dataset-oor-v2-2"
    model_weights_rel_path: "model"
    model_name: "best_yolo11m_coco_161024.pt"
    model_config_file: "train_data_augment_config.json" # can be an empty string or omitted entirely
    sweep_config_file: "sweep_config.json"
  outputs:
    project_datastore_path: "dataset_oor_v2_2"
    project_rel_path: "model"
    experiment_name: "yolo11m_base"  # subfolder name to store results in, can be an empty string or omitted entirely, will be ignored in sweep mode
  sweep_mode: False  # Set to true to run a hyperparameter sweep based on inputs/sweep_config_file
  sweep_trials: 1 # will be ignored in train mode

wandb:
  api_key: ""
  mode: "offline"
  entity: "a-lombardo-ggd-amsterdam"  # W&B entity to log the run to (default: null)
  project_name: "baas_v11"  # W&B project name

logging:
  loglevel_own: INFO  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "yolo_model_development_kit", "inference_pipeline", "model_conversion_pipeline", "performance_evaluation", "training_pipeline"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: WARNING
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
