[tool.poetry]
name = "yolo-model-development-kit"
version = "0.0.2"
description = "Project to develop a YOLO model using AzureML platform."
authors = [
    "Sebastian Davrieux <s.davrieux@amsterdam.nl>",
    "Diana Epureanu <d.epureanu@amsterdam.nl>",
    "Andrea Lombardo <a.lombardo@amsterdam.nl>",
    "Daan Bloembergen <d.bloembergen@amsterdam.nl>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
pre-commit = "^3.8.0"
aml_interface = { git = "https://github.com/Computer-Vision-Team-Amsterdam/AML-Interface.git", tag = "v1.1.2" }
azure-ai-ml = {version = "^1.2.0", source = "PyPI"}
azure-storage-blob = {version = "^12.19.0", source = "PyPI"}
cvtoolkit = { git = "https://github.com/Computer-Vision-Team-Amsterdam/CVToolkit.git", tag = "v2.0.3" }
matplotlib = {version = "^3.9.2", source = "PyPI"}
mldesigner = {version = "^0.1.0-beta.9", source = "PyPI"}
numpy = {version = "^1.24.2", source = "PyPI"}
pandas = {version = "^2.0.3", source = "PyPI"}
pycocotools = {version = "^2.0.7", source = "PyPI"}
torch = {version = "^2.2.1", source="torch"}
torchaudio = {version = "^2.2.1", source="torch"}
torchvision = {version = "^0.17.1", source="torch"}
ultralytics = {version = "^8.2.76", source = "PyPI"}
wandb = {version = "^0.17.5", source = "PyPI"}

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
